image: node:12.18.1

pipelines:
  default:
    - step:
        name: 'Build and Test'
        caches:
          - node
        script:
          - npm install
          #- npm run test -- --no-watch --no-progress
        artifacts:
          - node_modules/**
    - step:
        name: 'Lint'
        script:
          - npm run lint

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy
    # see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        trigger: 'manual'
        script:
          - './node_modules/@ionic/cli/bin/ionic build --configuration=staging'
          - 'tar -cf www-dist_staging_$BITBUCKET_BUILD_NUMBER.tar www/'
          - 'scp -P 2221 -r www-dist_staging_$BITBUCKET_BUILD_NUMBER.tar bitbucket@coachstaging.geton-training.de:'
          - 'ssh $COACHSTAGING tar -xf www-dist_staging_$BITBUCKET_BUILD_NUMBER.tar'
          - 'ssh $COACHSTAGING rm www-dist_staging_$BITBUCKET_BUILD_NUMBER.tar'
          - 'ssh $COACHSTAGING ls -la /var/www/app'
          - 'ssh $COACHSTAGING rm -rf /var/www/app'
          - 'ssh $COACHSTAGING mv ~/www /var/www/app'
          - 'ssh $COACHSTAGING ls -la /var/www/app'
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo 'not yet configured'
          - ./node_modules/@ionic/cli/bin/ionic build --configuration=production
