image: node:12.18.1

pipelines:
  default:
    - step:
        name: 'Build and Test'
        caches:
          - node
        script:
          - npm install
          #- npm run test -- --no-watch --no-progress
    - step:
        name: 'Lint'
        script:
          - npm run lint

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - ionic build --configuration=staging
          - ls -la
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - ionic build --configuration=production
