image: node:12.18.1

pipelines:
  default:
    - step:
        name: 'SSSHHH'
        script:
          - ssh bitbucket@coachstaging.geton-training.de -p 2221 'ls -la /var/www/app'
    - step:
        name: 'Build and Test'
        caches:
          - node
        script:
          - npm install
          #- npm run test -- --no-watch --no-progress
        artifacts:
          - node_modules/**
    - step:
        name: 'Lint'
        script:
          - npm run lint

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - ./node_modules/@ionic/cli/bin/ionic build --configuration=staging
          - ssh bitbucket@coachstaging.geton-training.de -p 2221 'ls -la /var/www/app'
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - ./node_modules/@ionic/cli/bin/ionic build --configuration=production
